### ISSUE TITLE
cont_rating_degree

### ISSUE THREAD

**Issue by qianyisun** [dsi-principles-prog/midterm-qianyisun#2]
When we need to consider to build a non-linear model (e.g. neural network, support vector machine), then we need to do categorization for content rating. At the same time, when you do categorization for content rating, it does show a more clear relationship between content rating and user rating. 

Therefore you can create a new feature function called cont_rating_degree to show what we want. When the value of content rating is the range between 0 and 6, then we can define it as "Low" level content rating. When the value of content rating is higher than six but its value is smaller than or equal to 12, then we define it as "Middle" level content rating. Finally, for the value that is higher than 12, I defined it as "High" level content rating.
Input: df(data frame), cont_rating(var), cont_rating_degree(col_name)
Output: create a new column on original dataset and the new column name is called cont_rating_degree

** Hint: we can refer to the two functions( in 30-feature-engineering) I left which might help you better create the function.**

Please write the function in chunk cont_rating_degree function in 30-feature-engineering on my repo.The expected outcome should look something like the two columns in the data frame below when you call the function:
<img width="242" alt="Screen Shot 2019-10-28 at 12 20 59 PM" src="https://user-images.githubusercontent.com/54040058/67701190-8212a900-f97d-11e9-9852-2addf9545ce8.png">

Please call the function and add the new variable into the dataset in prepare data code chunk in 40-modeling( You can see the hint in 40-modeling)

Please write the asserts/verifys function on the new feature in chunk test cont_rating_degree function in 40-modelling to ensure that its values only contain 'Low', 'Middle' and 'High'. ( You can see the hint in 40-modeling)

Thank you for your help.

**Comment by ninoyao** [comment]
added cont_rating_degree feature, closes #2

cont_rating_degree<-function(df,var,col_name){
 df<-df %>% 
    mutate(cont_rating_degree = case_when(
      {{var}} <= 6 ~ "Low",
      {{var}} <= 12 ~"Middle",
      TRUE ~ "High"
    )) %>% 
   select(cont_rating_degree,everything()) 
   names(df)[1]<-paste0(col_name) 
   df
}
